### ISSUE TITLE
Does not seem to work with two layers of modal screens.

### ISSUE THREAD

**Issue by mistenkt** [WoLewicki/react-native-window-view#2]
Heres the setup i'm currently using to be able to display toasts and a loader above modal screens. Works fine as long as its just one layer of modals, but if i push another modal on top of the current one, the content of `GlobalElements` will render in between the two modals and not on top.

Updating key on GlobalElements each time a modal is focused to cause a rerender, without that it would not render on top of the first modal layer either.

App.js
```JSX
<Provider store={store}>
    <GlobalElements>
        <ToastSystem/>
        <Loader/>
    </GlobalElements>
</Provider>
```

GlobalElements.js
```JSX
const GlobalElements = ({ children }) => {
    const modalFocusTimestamp= useSelector(state => state.modalFocus);
    return (
        <RNWindowView shown={true} key={modalFocusTimestamp}>
            {children}
        </RNWindowView>
    );
};
```

Each modalContainer uses this hook:

```JSX
import { useIsFocused } from '@react-navigation/native';
import { useEffect } from 'react';
import { dispatch } from '../../redux';

const useModalFocusDispatch = () => {
    const focused = useIsFocused();

    useEffect(() => {
        if (focused) dispatch('modal/focus', Date.now());
    }, [focused]);
};
```

**Comment by WoLewicki** [comment]
Did you apply those changes: https://github.com/WoLewicki/react-native-window-view/blob/master/example/ios/WindowViewExample/AppDelegate.m#L40 ? They should make the `RNWindowView` stay on top of the modals for their lifetime.

**Comment by mistenkt** [comment]
Completely missed that. Yes, that does seem to work, but still only in combination with the force rerender of `RNWindowView` every time a modal is focused. Not sure if that is intended or if theres is another part im missing.
